# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - name: Home
    url: /#top
    weight: 10
  - name: SALA 2026
    url: /sala2026
  - name: About Us
    url: /organization
    weight: 20
    weight: 30

footer:
  - identifier: home
    name: Home
    weight: 1
  - parent: home
    name: Home
    url: /
    weight: 1
  - identifier: tickets
    name: Events
    weight: 2
  - parent: tickets
    name: Register
    url: https://docs.google.com/forms/d/e/1FAIpQLScQp8GfLSdhmhW6mc4SggVgOa_SxYPmPGlaVLqS93Lur17ZZA/viewform
    weight: 3
  - identifier: aboutus
    name: About us
    weight: 3
  - parent: aboutus
    name: Organization
    url: /organization
  - parent: aboutus
    name: Our Story
    url: /brand
  - parent: aboutus
    name: Contact Us
    url: /contact
      #- identifier: legal
      #  name: Legal
      #  weight: 3
      #- parent: legal
      #  name: Privacy
      #  url: /privacy
      #  weight: 1
      #- parent: legal
      #  name: Terms
      #  url: /terms
      #  weight: 2
