# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark
  color: indigo

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'SALA.ai - Your living room conference for AI in Latin America.'
    twitter: 'TODO'
  analytics:
    google_tag_manager: 'G-HNCJ96GS56'
    google_analytics: 'G-HNCJ96GS56'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: false
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo_white.png"
    button:
      enable: true
      text: "Register Soon"
      url: "/register"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  blox: "sitemap"
  content:
    logo:
      text: "SALA '26"
    tagline: "Summit of AI in LatAm"
  design:
    columns: 4
  copyright:
    notice: '© {year} SALA'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Extensions
extensions:
  convertkit:
    # To use the ConvertKit Newsletter blox, provide your public API Key from your ConvertKit account settings page
    api_key: ""
